openapi: 3.0.0
info:
    title: Product API
    version: 1.0.0
    description: API for managing products
paths:
    /products:
        get:
            summary: Get a list of products
            parameters:
                - in: query
                  name: category
                  schema:
                      type: string
                  description: Category of the products
                - in: query
                  name: priceLessThan
                  schema:
                      type: integer
                  description: Maximum price of the products
                - in: query
                  name: page
                  schema:
                      type: integer
                      default: 1
                  description: Page number
                - in: query
                  name: limit
                  schema:
                      type: integer
                      default: 5
                  description: Number of products per page
            responses:
                '200':
                    description: A list of products
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        sku:
                                            type: string
                                            description: SKU of the product
                                        name:
                                            type: string
                                            description: Name of the product
                                        category:
                                            type: string
                                            description: Category of the product
                                        price:
                                            type: object
                                            properties:
                                                original:
                                                    type: integer
                                                    description: Original price of the product
                                        discount_percentage:
                                            type: integer
                                            description: Discount percentage of the product
                '400':
                    description: Invalid query parameter
                '500':
                    description: Internal server error
components:
    schemas:
        Product:
            type: object
            properties:
                sku:
                    type: string
                name:
                    type: string
                category:
                    type: string
                price:
                    type: object
                    properties:
                        original:
                            type: integer
                discount_percentage:
                    type: integer
