App\Application\Query\ProductQuery:
    properties:
        category:
            - NotBlank: ~
        priceLessThan:
            - Positive: ~
        page:
            - Positive: ~
        limit:
            - Range:
                min: 1
                max: 5
